services:
  todo-web:
    image: diamol/ch06-todo-list:latest
    ports:
      - 8080:80
    environment:
      - Database:Provider=Postgres
    networks:
      - app-net

  todo-db:
    image: diamol/postgres:11.5
    environment:
      - PGDATA:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-net

networks:
  app-net:
    name: todo-test

volumes:
  db_data:

secrets:
  todo-db-connection:
    file: ./config/postgres-connection.json