version: '3'

services:
  access-log:
    image: diamol/ch09-access-log
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.50"
          memory: 100M
    networks:
      app-net:
       
  iotd-api:
    image: diamol/ch09-image-of-the-day
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "1"
          memory: 200M
    ports:
      - 8088:80
    networks:
      app-net:

  image-gallery:
    image: diamol/ch09-image-gallery
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.75"
          memory: 75M
    networks:
      app-net:
    
networks:
  app-net:

