FROM diamol/golang AS builder

COPY main.go .
RUN go build -o /web/server
RUN chmod +x /web/server

FROM diamol/base

ENV USER=sixeyed
EXPOSE 80
CMD ["/web/server"]

WORKDIR web
COPY --from=builder /web/server /web
COPY index.html .