version: "3.7"

services:
  todo-app:
    image: diamol/ch06-todo-list
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - Database:Provider=postgres
    depends_on:
      - todo-db
    secrets:
      - source: postgres-connection
        target: /app/config/secrets.json
  todo-db:
    image: diamol/postgres:11.5
    volumes:
      - ./data:/var/lib/postgresql/data


secrets:
  postgres-connection:
    file: ./config/secrets.json