global:
	scrape_interval: 10s

scrape_configs:
	- job_name: "image-gallery"
		metric_path: /metrics
		static_configs:
			- targets: ["image-gallery"]

	- job_name: "iotd-api"
		metric_path: /actuator/prometheus
		static_configs:
			- targets: ["iotd"]

	- job_name: "access-log"
		metrics_path: /metrics
		dns_sd_configs:
			- names:
				- accesslog
					type: A
					port: 80